### ISSUE TITLE
fr model has an extra embedded image 

### ISSUE THREAD

**Issue by jimmy-tfp** [alexa/skill-sample-nodejs-audio-player#134] opened 2018-12-19 23:35 UTC
If you look at "AudioAssets.ts" it seems there is an extra image object in the json:

```

let en = {
    card: {
        title: 'My Radio',
        text: 'Less bla bla bla, more la la la',
        image: {
            largeImageUrl: 'https://alexademo.ninja/skills/logo-512.png',
            smallImageUrl: 'https://alexademo.ninja/skills/logo-108.png'
        }
    },
    url: 'https://audio1.maxi80.com',
    startJingle: 'https://s3-eu-west-1.amazonaws.com/alexa.maxi80.com/assets/jingle.m4a'
};

let fr = {
    card: {
        title: 'My Radio',
        text: 'Moins de bla bla bla, plus de la la la',
        image: {
            image: {
                largeImageUrl: 'https://alexademo.ninja/skills/logo-512.png',
                smallImageUrl: 'https://alexademo.ninja/skills/logo-108.png'
            }
    
        }
    },
    url: 'https://audio1.maxi80.com',
    startJingle: 'https://s3-eu-west-1.amazonaws.com/alexa.maxi80.com/assets/jingle.m4a'
};

```

**Comment by aszk** [comment] 2023-04-13 22:36
This repository is simplified to en-US model only. I am closing this because the issue is not relevant anymore.

**Closed as completed by aszk** 2023-04-13 22:36 UTC
