### ISSUE TITLE
Alexa keeps to tell me "problem with the response of the skill"

### ISSUE THREAD

**Issue by dakoller** [alexa/skill-sample-nodejs-audio-player#44] opened 2017-07-22 15:46 UTC
The skeleton of the skill works now well... so all non-audio commands "somehow" work.

However whenever I would expect some audio to be played i get the german pendant of "There was a problem with the response, which this skill gave back".
But my cloudwatch logs do tell me not, that there was an error.

..where and how can i put the skill output into cloudwatch logs to see the feedback?

**Comment by n2questdev** [comment] 2017-08-09 04:55
Hi - I had similar issues, I've fixed with the following:
1. APP_ID vs appId. make sure to have **_alexa.APP_ID_** = 'your_skill_id;
2. Audio links must use https://
3. I haven't got complete grip on this, but the issue is with canThrowCard function in stateHandlers.js. For now I'm returning **_true_** always commenting all the logic from original author
4. Sometimes updating lambda function doesn't reflect immediately. Give it few minutes soaking time before testing again.

Hope this helps and good luck!

**Comment by gubendran-tech** [comment] 2017-08-13 02:52
Hi @ajuluri 

I corrected the alexa.APP_ID and verified the https:// link. I could play the link from the browser. I also updated canThrowCard function to return always true and waited for sometime and tested the code and no luck.

Is there any options you could suggest?  Below is the directives from test simulator

"directives": [
        {
          "playBehavior": "REPLACE_ALL",
          "audioItem": {
            "stream": {
              "token": "0",
              "url": "https://s3.amazonaws.com/tamilcomedydialogues/Gowndamani+-+Azhagu+Raja.mp3",
              "offsetInMilliseconds": 0
            }
          }
        },

Thanks,
Gubendran

**Comment by jasonabradley** [comment] 2017-10-11 13:13
@dakoller 

You can add a line inside the intents to capture to CloudWatch Logs what is coming in to the function.

console.log(this.event);

**Comment by sebsto** [comment] 2018-01-23 11:57
Have a look at https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/single-stream/lambda/src/index.js#L11 to demonstrate how you can capture the full request / response.  

Also, the audio player directive are only supported on actual devices.  EchoSim or the web simulator will not play any song.

I am closing this now, feel free to re-open with more details if you still are facing this issue.

**Closed as completed by sebsto** 2018-01-23 11:57 UTC
