### ISSUE TITLE
After saying Next, audio player will not continue after next audio ,please help

### ISSUE THREAD

**Issue by ranjithavav** [alexa/skill-sample-nodejs-audio-player#115] opened 2018-08-05 02:28 UTC
Team,
next is working and it streams next audio but after that it stops.

And also resume command not accepting , saying "this is not a valid command'

kindly help me anyone

**Comment by sebsto** [comment] 2018-08-20 12:02
Hello,
Thank you for trying out our sample code.  Which skill are you reporting this for ?  The Multiple Stream or Single Stream ?
Are you using the code "as is" or did you do any modification ?  If you did modify the code, can you share your changes or the git repo with the updated code so that we can have a look ?
In general, any more details that will help us to understand the root cause of the problem will be appreciated.
Cheers

**Comment by ranjithavav** [comment] 2018-08-20 12:17
Thanks for your comments, Issue is for multi stream and I am using same code only .
If we are playing with say next command it's playing continuosly ,but if we says next it's play next then stops play.

**Comment by sebsto** [comment] 2018-08-20 12:28
Thank you for the details - I will have a look and report back

**Comment by allthepies** [comment] 2018-08-30 11:39
There's a bug around the resetting of the nextStreamEnqueued flag.

If an audio track is stopped via a "next", "previous" etc voice command then the nextStreamEnqueued flag isn't reset and when the next PlaybackNearlyFinished event occurs then the event handler checks the flag, sees it's still set and exits the handler without enqueuing the next track.

Change the play function in the controller object as follows

```
// Existing code
const playBehavior = 'REPLACE_ALL';
const podcast = constants.audioData[playOrder[index]];
const token = playOrder[index];

// Add the following line
playbackInfo.nextStreamEnqueued = false;
```

**Comment by ananddevsingh** [comment] 2018-08-31 09:45
@allthepies , @sebsto . Thank you so much. I confirm, the issue is fixed now.

**Comment by sebsto** [comment] 2018-09-02 08:27
Thank you for the fix.  Merged now

**Closed as completed by sebsto** 2018-09-02 08:27 UTC
Labels: help wanted
