### ISSUE TITLE
Cannot change invocation name

### ISSUE THREAD

**Issue by gergokekesi** [alexa/skill-sample-nodejs-audio-player#100] opened 2018-04-27 10:43 UTC
Hi! I tried everything I could be I don't seem to be able to change the invocation name so I could use the template for my own skill. I have changed every reference I could find to "audio player" to "my own name" but no matter if I re-deploy or change the name in the alexa console I can only refer to the skill by the name "audio-player". Also, is there a way to play non-HTTPS links? 

Thank you!

PS: Otherwise this repo is super useful!

**Comment by gergokekesi** [comment] 2018-04-27 21:44
So the weird thing is that I left the thing for a while and for the fun of it I tried to see if it worked and it did! Somehow it took Amazon a while to actually update the invocation name... weird. Why could this have happened?

**Comment by ranjithavav** [comment] 2018-08-05 03:12
you can change the invocation name in developer.amazon.com

Edit skill under that you can see invocation and change
![capture](https://user-images.githubusercontent.com/33387735/43682211-7aab6930-988b-11e8-901f-3103e9424bf2.PNG)

**Comment by sebsto** [comment] 2018-08-20 12:06
Thank you @avrpayyyur  for helping - looks like the problem is solved.  Closing this issue.

**Closed as completed by sebsto** 2018-08-20 12:06 UTC

**Comment by iamkfred** [comment] 2018-08-30 16:01
I'm having the same issue.  I've changed my invocation name, saved, built.  minutes after getting the build complete message, it's still responding to the old invocation name and not the new.  I think there are propagation issues with the build process.  Done doesn't mean done.

**Comment by sebsto** [comment] 2018-08-30 16:52
When you change the invocation name, you need also to disable and reenable the skill on your account. Just turn off the test switch and turn it on again 

--Seb

**Comment by lilithxxx** [comment] 2018-09-18 09:24
>When you change the invocation name, you need also to disable and reenable the skill on your account. Just turn off the test switch and turn it on again

@sebsto Thanks it solved the problem.

**Comment by stevage** [comment] 2018-10-21 23:37
>When you change the invocation name, you need also to disable and reenable the skill on your account. Just turn off the test switch and turn it on again

That worked for me. I would call this a bug, as there is no indication anywhere (eg, when changing the invocation name) that this is required.

**Comment by zjj1002** [comment] 2018-10-26 05:53
Definitely  it's a bug. spent two hour for me to find what's wrong.

**Comment by pedrini77** [comment] 2018-11-06 14:39
Bug (or lack of an informational message). I spent a good 45min trying to figure this out too.

**Comment by mmahmad** [comment] 2019-04-09 13:00
Can confirm this issue still exists.

**Comment by jwolsborn** [comment] 2019-05-31 03:58
> 
> 
> > When you change the invocation name, you need also to disable and reenable the skill on your account. Just turn off the test switch and turn it on again
> 
> That worked for me. I would call this a bug, as there is no indication anywhere (eg, when changing the invocation name) that this is required.

Where do I do this at?  I'm having the same issue

**Comment by sebsto** [comment] 2019-05-31 06:03
you can do that either in the Alexa developer console (developer.amazon.com) in the Test tab.  Or on the Alexa App (on mobile or alexa.amazon.com) in the Skills section.

**Comment by sharanken** [comment] 2019-05-31 06:25
can anyone tell me about this issue https://github.com/alexa/skill-sample-nodejs-audio-player/issues/149#issue-441232779

**Comment by sonhanguyen** [comment] 2019-10-05 12:33
did anyone bother to add the "disable/enable again" instruction into some documentation somewhere when this issue was "resolved"?
